const Users = [
    {
        taskID: 87767,
        taskName: 'PS Implementation - Immigration incl visa,work permit',
        includeHoliday: 'N',
        emergencyFlag: 'N',
        taskType: 100,
        status: 1,
        clientName: 'Shanghai Yongda Finance Leasing Co., Ltd   ',
        codeNum: '915774',
        executeUserID: null,
        executeFullName: null,
        executeTelAndExt: null,
        executeTitle: null,
        executeCellphone: null,
        executeDepName: null,
        executeEmail: null,
        requestUserID: 2,
        requestFullName: 'Xu, Serena J.F. (SH/TAX)',
        requestTelAndExt: 'tel:+862122124632;ext=6204632',
        requestTitle: 'Tax Manager',
        requestCellphone: '15821342029',
        requestDepName: 'SHW Tax TMS',
        requestEmail: 'serena.xu@kpmg.com',
        approver1UserID: null,
        approver1FullName: null,
        approver1TelAndExt: null,
        approver1Title: null,
        approver1Cellphone: null,
        approver1DepName: null,
        approver1Email: null,
        approver2UserID: null,
        approver2FullName: null,
        approver2TelAndExt: null,
        approver2Title: null,
        approver2Cellphone: null,
        approver2DepName: null,
        approver2Email: null,
        beginDate: '2020-08-04 00:00:00',
        endDate: '2020-08-29 00:00:00',
        totalHours: 8.0,
        todayHours: null,
        taskReviewFlag: 0,
        docFileFlag: 0,
        newMsgFlag: null,
        approvalStatus: null,
        tenantName: null,
    },
    {
        taskID: 87766,
        taskName: 'PS Implementation - Immigration incl visa,work permit',
        includeHoliday: 'N',
        emergencyFlag: 'N',
        taskType: 100,
        status: 1,
        clientName: 'Shanghai Yongda Finance Leasing Co., Ltd   ',
        codeNum: '915774',
        executeUserID: null,
        executeFullName: null,
        executeTelAndExt: null,
        executeTitle: null,
        executeCellphone: null,
        executeDepName: null,
        executeEmail: null,
        requestUserID: 2,
        requestFullName: 'Xu, Serena J.F. (SH/TAX)',
        requestTelAndExt: 'tel:+862122124632;ext=6204632',
        requestTitle: 'Tax Manager',
        requestCellphone: '15821342029',
        requestDepName: 'SHW Tax TMS',
        requestEmail: 'serena.xu@kpmg.com',
        approver1UserID: null,
        approver1FullName: null,
        approver1TelAndExt: null,
        approver1Title: null,
        approver1Cellphone: null,
        approver1DepName: null,
        approver1Email: null,
        approver2UserID: null,
        approver2FullName: null,
        approver2TelAndExt: null,
        approver2Title: null,
        approver2Cellphone: null,
        approver2DepName: null,
        approver2Email: null,
        beginDate: '2020-08-04 00:00:00',
        endDate: '2020-08-29 00:00:00',
        totalHours: 8.0,
        todayHours: null,
        taskReviewFlag: 0,
        docFileFlag: 0,
        newMsgFlag: null,
        approvalStatus: null,
        tenantName: null,
    },
    {
        taskID: 87765,
        taskName: 'PS Implementation - Immigration incl visa,work permit',
        includeHoliday: 'N',
        emergencyFlag: 'N',
        taskType: 100,
        status: 1,
        clientName: 'Shanghai Yongda Finance Leasing Co., Ltd   ',
        codeNum: '915774',
        executeUserID: null,
        executeFullName: null,
        executeTelAndExt: null,
        executeTitle: null,
        executeCellphone: null,
        executeDepName: null,
        executeEmail: null,
        requestUserID: 2,
        requestFullName: 'Xu, Serena J.F. (SH/TAX)',
        requestTelAndExt: 'tel:+862122124632;ext=6204632',
        requestTitle: 'Tax Manager',
        requestCellphone: '15821342029',
        requestDepName: 'SHW Tax TMS',
        requestEmail: 'serena.xu@kpmg.com',
        approver1UserID: null,
        approver1FullName: null,
        approver1TelAndExt: null,
        approver1Title: null,
        approver1Cellphone: null,
        approver1DepName: null,
        approver1Email: null,
        approver2UserID: null,
        approver2FullName: null,
        approver2TelAndExt: null,
        approver2Title: null,
        approver2Cellphone: null,
        approver2DepName: null,
        approver2Email: null,
        beginDate: '2020-08-04 00:00:00',
        endDate: '2020-08-29 00:00:00',
        totalHours: 8.0,
        todayHours: null,
        taskReviewFlag: 0,
        docFileFlag: 0,
        newMsgFlag: null,
        approvalStatus: null,
        tenantName: null,
    },
    {
        taskID: 87739,
        taskName: 'Tax technology project',
        includeHoliday: 'N',
        emergencyFlag: 'N',
        taskType: 100,
        status: 2,
        clientName: 'Bank of Hangzhou 杭州银行  ',
        codeNum: '946859',
        executeUserID: 446,
        executeFullName: 'Gao, Mandy (SH/TAX)',
        executeTelAndExt: 'tel:+862122122013;ext=6202013',
        executeTitle: 'Assistant Manager',
        executeCellphone: '',
        executeDepName: 'SHW Tax PRC Tax Pool',
        executeEmail: 'mandy.gao@kpmg.com',
        requestUserID: 2,
        requestFullName: 'Xu, Serena J.F. (SH/TAX)',
        requestTelAndExt: 'tel:+862122124632;ext=6204632',
        requestTitle: 'Tax Manager',
        requestCellphone: '15821342029',
        requestDepName: 'SHW Tax TMS',
        requestEmail: 'serena.xu@kpmg.com',
        approver1UserID: null,
        approver1FullName: null,
        approver1TelAndExt: null,
        approver1Title: null,
        approver1Cellphone: null,
        approver1DepName: null,
        approver1Email: null,
        approver2UserID: null,
        approver2FullName: null,
        approver2TelAndExt: null,
        approver2Title: null,
        approver2Cellphone: null,
        approver2DepName: null,
        approver2Email: null,
        beginDate: '2020-08-03 00:00:00',
        endDate: '2020-09-05 00:00:00',
        totalHours: 122.5,
        todayHours: 8.0,
        taskReviewFlag: 0,
        docFileFlag: 1,
        newMsgFlag: null,
        approvalStatus: null,
        tenantName: null,
    },
    {
        taskID: 87738,
        taskName: 'Tax technology project',
        includeHoliday: 'N',
        emergencyFlag: 'N',
        taskType: 100,
        status: 2,
        clientName: 'Bank of Hangzhou 杭州银行  ',
        codeNum: '946859',
        executeUserID: 217,
        executeFullName: 'Yuan, Ada (SH/TAX)',
        executeTelAndExt: 'tel:+862122124516;ext=6204516',
        executeTitle: 'Assistant Manager',
        executeCellphone: null,
        executeDepName: 'SHW Tax PRC 1',
        executeEmail: 'ada.yuan@kpmg.com',
        requestUserID: 2,
        requestFullName: 'Xu, Serena J.F. (SH/TAX)',
        requestTelAndExt: 'tel:+862122124632;ext=6204632',
        requestTitle: 'Tax Manager',
        requestCellphone: '15821342029',
        requestDepName: 'SHW Tax TMS',
        requestEmail: 'serena.xu@kpmg.com',
        approver1UserID: null,
        approver1FullName: null,
        approver1TelAndExt: null,
        approver1Title: null,
        approver1Cellphone: null,
        approver1DepName: null,
        approver1Email: null,
        approver2UserID: null,
        approver2FullName: null,
        approver2TelAndExt: null,
        approver2Title: null,
        approver2Cellphone: null,
        approver2DepName: null,
        approver2Email: null,
        beginDate: '2020-08-03 00:00:00',
        endDate: '2020-08-31 00:00:00',
        totalHours: 68.0,
        todayHours: 8.0,
        taskReviewFlag: 0,
        docFileFlag: 0,
        newMsgFlag: null,
        approvalStatus: null,
        tenantName: null,
    },
];

export default Users;
